services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports: ["6333:6333"]
    volumes: ["qdrant_data:/qdrant/storage"]

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gptu
      POSTGRES_PASSWORD: gptu
      POSTGRES_DB: gptu
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

volumes:
  qdrant_data:
  pg_data:
